version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "scala"
enabled = true